# -*- coding: utf-8 -*-
"""shobana.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ePVFc6EkPvLuPaKI4lUWAbxE1ZFdZgJ1
"""

# disease_prediction.py

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Step 1: Load Data
df = pd.read_csv('patient_data.csv')  # Replace with your dataset path

# Step 2: Explore Data
print("First 5 rows:\n", df.head())
print("Missing values:\n", df.isnull().sum())
print("Class distribution:\n", df['disease'].value_counts())

# Step 3: Preprocessing
df.fillna(method='ffill', inplace=True)  # Basic imputation
X = df.drop(['d…